# Generated by Django 4.1.3 on 2023-01-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0003_alter_trek_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='media/'),
        ),
    ]
