# Generated by Django 4.1.3 on 2023-01-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0005_trek_users_alter_trek_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trek',
            old_name='users',
            new_name='participants',
        ),
    ]
