# Generated by Django 4.1.3 on 2023-01-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0006_rename_users_trek_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='trek',
        ),
        migrations.AddField(
            model_name='trek',
            name='comments',
            field=models.ManyToManyField(related_name='treks', to='treks.comment'),
        ),
    ]
