# Generated by Django 4.1.5 on 2023-01-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0009_alter_comment_user_alter_trek_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='category',
            field=models.ManyToManyField(default=[1], related_name='treks', to='treks.category'),
        ),
    ]
